import { ScrollView, Switch } from "std-widgets.slint";
export component MainWindow inherits Window {
    ScrollView {

        VerticalLayout {
            spacing: 10px;

            padding: 10px;
            Switch {
                text: "Switch";
            }

            Switch {
                text: "Switch2";
            }

            Rectangle {
                width: 100%;
                height: 500px;
                background: blanchedalmond;
                border-radius: 10px;
            }
        }
    }
}
