import { ScrollView, Switch, HorizontalBox, StyleMetrics, ListView, VerticalBox, Palette } from "std-widgets.slint";

struct booklistentry {
    id: string,
}

component bookentry inherits VerticalLayout {
    in property <string> id;

    Rectangle {
        Rectangle {
            background: Palette.background;
            border-radius: 10px;
            height: 50px;
            Text {
                text: id;
                font-size: 14px;
                font-family: "monospace";
                vertical-alignment: center;
                horizontal-alignment: left;
            }
        }
    }
}

export component MainWindow inherits Window {
    in property <[booklistentry]> entries: [{ id: "" }];

    VerticalBox {
        spacing: 10px;
        padding: 10px;

        Switch {
            text: "Show Details";
        }

        Switch {
            text: "Auto Refresh";
        }

        Rectangle {
            background: Palette.background;
            ListView {

                for entry in entries: bookentry {
                    padding: 20px;
                    id: entry.id;
                }
            }
        }
    }
}
