import { ScrollView, Switch, HorizontalBox, StyleMetrics, ListView, VerticalBox } from "std-widgets.slint";

struct booklistentry {
    id: string,
}

component bookentry inherits Rectangle {
    in property <string> id;

    border-radius: 6px;
    background: slategray;

    Text {
        text: id;
        font-size: 14px;
        font-family: "monospace";
        vertical-alignment: center;
        horizontal-alignment: left;
    }
}

export component MainWindow inherits Window {
    in property <[booklistentry]> entries: [{ id: "" }];

    VerticalBox {
        // alignment: start;
        spacing: 10px;
        padding: 10px;

        Switch {
            text: "Show Details";
        }

        Switch {
            text: "Auto Refresh";
        }

        ListView {
            for entry in entries: bookentry {
                padding: 10px;
                id: entry.id;
            }
        }
    }
}
